subscribe:
  scmUrls:
    - git@github.com:wahapo/subscribe-2.git: [ ~release ]
  
jobs:
  main:
    requires: [ ~pr, ~commit, ~subscribe ]
    image: node:10
    steps:
      - ls
      - init: |
          SDLOCAL_VERSION=`meta get sd.release.name | sed s/^v//`
          echo $SDLOCAL_VERSION
          wget "https://github.com/screwdriver-cd/sd-local/releases/download/v${SDLOCAL_VERSION}/sd-local_${SDLOCAL_VERSION}_checksums.txt" -O $SD_ARTIFACTS_DIR/checksums.txt
          cat $SD_ARTIFACTS_DIR/checksums.txt
